version: '3'
networks:
  web2:
    external: true

services:
  proxy:
    image: 'traefik:2.3'
    container_name: 'proxy'
    command:
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--providers.docker=true'
      - '--providers.docker.network=web2'
      - '--certificatesresolvers.le.acme.email=johanh@stackpoint.se'
      - '--certificatesresolvers.le.acme.storage=/acme.json'
      - '--certificatesresolvers.le.acme.tlschallenge=true'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './acme.json:/acme.json'
    networks:
      - 'web2'
    ports:
      - '80:80'
      - '443:443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

