version: '3'
networks:
  web:
    external: true

services:
  proxy:
    image: 'traefik:2.5'
    container_name: 'proxy'
    restart: 'always'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './config:/config'
      - './traefik.yml:/traefik.yml'
    networks:
      - 'web'
    ports:
      - '80:80'
      - '443:443'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

