version: '2'
networks:
    web:
        external: true
services:
    proxy:
        image: 'traefik:1.7-alpine'
        container_name: 'proxy'
        restart: 'always'
        ports:
            - '80:80'
        networks:
            - 'web'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './traefik.toml:/traefik.toml'
