debug = true

logLevel = "INFO"
defaultEntryPoints = ["http"]

[accessLog]
enabled=true

[entryPoints]
  [entryPoints.http]
  address = ":80"

[api]
entryPoint = "traefik"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedByDefault = false
