log:
  level: 'INFO'

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls: {}

providers:
  file:
    directory: '/config/domains'
    watch: true
  docker: 
    network: 'web'
    exposedByDefault: false

