debug = true

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[accessLog]
enabled=true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/dev.crt"
      keyFile = "/certs/dev.key"

[api]
entryPoint = "traefik"
dashboard = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "localhost"
watch = true
exposedByDefault = false
