log:
  level: 'INFO'

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls: {}

providers:
  file:
    filename: '/certs/config.yml'
    watch: true
  docker: 
    exposedByDefault: false

